# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd461870e915098305387e4f6adee7c78f7ca6b3ebfc0baac712af7949e6121b1d5b3f16cb28ea918c19c1667afefac0e73c1ca6b85371f2a2c7202c8cb9e028

test:
  secret_key_base: 3c293ffd391c6406206f07c1e3f9e97c468839e6ecc65ff3d2107718d49b341708e40c91639658d055300397a00091ba73e99ad33283ca62aeea1e25d79809fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
